declare module 'rehype-citation'
declare module 'rehype-slug'
declare module 'rehype-autolink-headings'
declare module 'rehype-katex'
declare module 'rehype-prism-plus'
declare module 'rehype-preset-minify'
declare module 'pliny/mdx-components'
declare module 'pliny/utils/contentlayer'
declare module 'pliny/utils/formatDate'
declare module 'pliny/ui/TOCInline'
declare module 'pliny/ui/Pre'
declare module 'pliny/mdx-components'
declare module 'pliny/ui/BlogNewsletterForm'
// import rehypeSlug from 'rehype-slug'
// import rehypeAutolinkHeadings from 'rehype-autolink-headings'
// import rehypeKatex from 'rehype-katex'
// import rehypeCitation from 'rehype-citation'
// import rehypePrismPlus from 'rehype-prism-plus'
// import rehypePresetMinify from 'rehype-preset-minify'
// import siteMetadata from './src/data/siteMetadata'