export default [
    {
        title: 'Codeigniter SMM',
        description: 'My first SMM Panel in 2019, SMM Panel is website or service for buying and selling social media needs',
        image: '/static/images/project-1.jpg',
        link: '',
        tags: ['Codeigniter', 'PHP', 'Bootstrap 4', 'jQuery'],
        is_github: false,
        github_link: '',
    },
    {
        title: 'VA Luna Online',
        description: 'Private Server Luna Online',
        image: '/static/images/project-2.jpg',
        link: '',
        tags: ['Laravel', 'PHP', 'Bootstrap 4', 'jQuery'],
        is_github: false,
        github_link: '',
    },
    {
        title: 'Rin Luna Plus',
        description: 'Private Server Luna Online',
        image: '/static/images/project-4.jpg',
        link: '',
        tags: ['Laravel', 'PHP', 'Bootstrap 4', 'jQuery'],
        is_github: false,
        github_link: '',
    },
    {
        title: 'Eclipse Luna Online',
        description: 'Private Server Luna Online',
        image: '/static/images/project-3.webp',
        link: '',
        tags: ['Laravel', 'PHP', 'Bootstrap 4', 'jQuery'],
        is_github: false,
        github_link: '',
    },
    {
        title: 'Omega Luna',
        description: 'Private Server Luna Online',
        image: '/static/images/project-5.png',
        link: '',
        tags: ['Laravel', 'PHP', 'TailwindCSS', 'Vue.js'],
        is_github: false,
        github_link: '',
    },
    {
        title: 'Portofolio',
        description: 'My Portofolio Created With NextJS and TailwindCSS',
        image: '/static/images/project-6.png',
        link: 'https://portofolio-eight.vercel.app/',
        tags: ['TailwindCSS', 'Next.js'],
        is_github: true,
        github_link: 'https://github.com/swiftalker/portofolio',
    },
    {
        title: 'Rin Luna Online',
        description: 'Private Server Luna Online',
        image: '/static/images/project-7.jpeg',
        link: '',
        tags: ['Laravel', 'PHP', 'TailwindCSS', 'Alpine.js', 'Livewire'],
        is_github: false,
        github_link: '',
    },
    {
        title: 'RA Luna Online',
        description: 'Private Server Luna Online MMORPG',
        image: '/static/images/project-8.png',
        link: 'https://ralunaonline.com',
        tags: ['Laravel', 'PHP', 'TailwindCSS', 'Alpine.js', 'Livewire'],
        is_github: false,
        github_link: '',
    },
    {
        title: 'Crowdfunding',
        description: 'Crowdfunding Base on Laravel',
        image: '/static/images/project-9.png',
        link: '',
        tags: ['Laravel', 'PHP', 'TailwindCSS', 'Alpine.js', 'Livewire'],
        is_github: false,
        github_link: '',
    }
]